import data from "./media.generated.json";

export type Media = { src: string; w: number; h: number; blur: string; post: string; date: string };

const all = data as Record<string, Media>;

/** Instagram media by `{postCode}-{index}`, e.g. `Ddh1xvnG7AR-4`. Generated by scripts/build-media.mjs. */
export function media(id: string): Media {
  const m = all[id];
  if (!m) throw new Error(`Unknown media id "${id}". Run node scripts/build-media.mjs?`);
  return m;
}

export const VIDEO = {
  runway: { src: "/media/video/runway.mp4", poster: "/media/video/runway-poster.webp", w: 1280, h: 720 },
  forgiven: { src: "/media/video/forgiven.mp4", poster: "/media/video/forgiven-poster.webp", w: 1280, h: 720 },
} as const;

export const INSTAGRAM = "https://www.instagram.com/children_ofthelight/";
